on:
  pull_request:
    paths:
      - "**/*.tf"

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate Terraform docs for each directory
        run: |
          find . -type f -name "*.tf" -exec dirname {} \; | sort -u | while read -r directory; do
            echo "Generating Terraform docs for $directory"
            terraform-docs --version
            terraform-docs markdown "${directory}" >> "${directory}/README.md"
            git -C "${directory}" add README.md
            git -C "${directory}" commit -m "Update Terraform docs"
          done
