name: Generate terraform docs
on:
  pull_request:
    paths:
      - "**/*.tf"

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate and commit Terraform docs for each directory
        run: |
          find . -type f -name "*.tf" -exec dirname {} \; | sort -u | while read -r directory; do
            echo "Generating Terraform docs for $directory"
            terraform-docs/gh-actions@v1.1.0 --output-file "${directory}/README.md" "${directory}"
            git -C "${directory}" add README.md
            git -C "${directory}" commit -m "Update Terraform docs"
          done
