name: Generate terraform docs

on:
  pull_request:

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate Terraform docs terraform-modules
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          working-dir: terraform-modules
          recursive: true
          recursive-path: .
          output-file: README.md
          output-method: inject
          git-push: "true"
      - name: Generate Terraform docs terraform-incubator
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          working-dir: terraform-incubator
          recursive: true
          recursive-path: "**/*.tf"
          output-file: README.md
          output-method: inject
          git-push: "true"
